### PR TITLE
add converter between baseband file handle style and psrfits

### PR DESCRIPTION
**Pull request by luojing1211**
This PR is trying to bridge the Scintillometry style of files and PSRFITS. PSRFITS is tricky to handle, so if anyone has any good idea on the code structure please feel free to comment below.

### CODE REVIEW

**Comment by mhvk** [comment]
@luojing1211 - great to see this initial start - let's discuss next week when I'm back.

In the meantime, it may be good to think a bit about both sides: writing a stream to a PSRFITS file, and using a PSRFITS file as a stream.

For using PSRFITS as a stream, see #63 on how one can use an array as a stream - the difference here would be to get the relevant `start_time`, `sample_rate`, etc., out of the PSRFITS file (which I think you're already moving towards).

More generally, this is one case where I think it will really help to write test cases first. I would say something like:
1. Write a PSRFITS file using its own interface.
2. Check that it can be used as a stream.
3. Write that stream to a new PSRFITS file and show that it contains the same information.
4. Convert a sample file to a PSRFITS file and show that its contents are OK.

**Comment by luojing1211** [comment]
Hi Marten, 
Thanks for your input. I was actually asking myself the same questions. However, when I learn more about PSRFITS I feel how tricky it is. 
1. PSRFITS provide a lot of versions of HDU tables.  One of the data ones is called Subintegration HDU with predefined cards and fields. It is mainly for pulsar folding and searching. It is perfect for the folded data, but for the waterfall, there may need some tweaking. If we want to use it on the secondary spectrum, it may be necessary to build another template for it. 

2.  Translating between the stream and PSRFITS SUBINT HDU needs more work. A lot of information (start_time, frequency, etc.) has to be manually converted from PSRFITS, vice versa.  `pdat` is not that complete. Maybe it is the time to propose the and updated version of `pdat`, because a lot of those conversions (get_start_time, get_frequency_axis, etc) should happen at the `pdat` level, not the scintillomery pipeline.  

3. I think a strong test case is we write one PSRFITS file and read it from PSRarchive. I don't know how to make this a unittest yet, but internally it will be a strong test.

**Comment by mhvk** [comment]
OK, thanks for the summary.  Sounds like we should start by writing a folded profile, then!

**Comment by luojing1211** [comment]
This PR is taken place by #94

**Pull request closed without merging**
