### PR TITLE
ReadtheDocs build environment change.

### PR DESCRIPTION
**Pull request by cczhu**
Hoping it fixes RTD build errors.

### CODE REVIEW

**Comment by mhvk** [comment]
I'm very confused: why does `baseband` itself need to be listed as a dependency?

**Comment by cczhu** [comment]
This is a somewhat crapshoot attempt at fixing the ReadTheDocs build error:
```
Fetching package metadata ...............

ResolvePackageNotFound: 
  - baseband
```
I'm not sure if we also need to include pyfftw.

**Comment by mhvk** [comment]
Ah, sorry, this is `scintillometry`, so yes, of course we need to download baseband. And I think we need `pyfftw` as well.  But I'll merge this so we can see what the next error message is!

**Comment by cczhu** [comment]
RTD failed on that build too.

I just realized that I can totally push branches to upstream, like with Baseband, so can directly experiment without pull requests!  I'll do that until I've created a fix.

**Pull request merged**
