### PR TITLE
PSRFITS PSRHdu data write

### PR DESCRIPTION
**Pull request by luojing1211**
This PR is a small upgrade on the PSRFITS PSRSUBINT hdu. Here are what it does:
1. Adds the data columns 
2. Allows one set data to the data columns
3. Covert an HDU to an astropy io hdulist

### CODE REVIEW

**Comment by mhvk** [comment]
@luojing1211 - There was a failure in the docs that was unrelated to your PR, which I fixed separately (in #124, though it really is an upstream issue: https://github.com/numpy/numpy/issues/14359), and one in your use of pytest's `tmpdir` (which I think was solved in more recent python). A rebase and a quick edit fixed those.

There were also some warnings which I felt represented a real problem: that if 'TSUBINT' is not set, `self.sample_rate` is infinite. For now, I just use 'TSUBINT' directly where possible (last commit).

I now hope to have a bit more of a look at the rest.

**Comment by mhvk** [comment]
@luojing1211 - I forced-pushed my edits again - this includes all of your commits (but rebased to squash together PEP fixes, etc) as well as my commit that makes the tests pass. You'll probably need to restart your branch based on this rather than try to merge master.

**Comment by mhvk** [comment]
@luojing1211 - I pushed my additions (and rebased). The main change is that in the parser, I now create full HDU headers, which makes dealing with them inside `hdu.py` much simpler.

The one part I'm not very happy with is the initialization of an empty header - I think one should be forced to give the sample shape already. But since `hdu.py` will be hidden from the user anyway, we can deal with that later.

**Comment by luojing1211** [comment]
Ok, I will take a look and move forward.

**Comment by mhvk** [comment]
Great. I just pushed another commit to get rid of the old-python failure. (We should go up to python 3.6, but that is a separate issue.)

**Comment by mhvk** [comment]
Sorry, it seems I messed up the pep8 fix; I'll force-push a fix in a bit. It may be easiest to just
```
git fetch origin
git checkout origin/hdu_data_write
git branch -D hdu_data_write
git checkout -b hdu_data_write
```
before making further changes.

**Comment by mhvk** [comment]
Looks like PINT needs a newer numpy... Changed `.travis.yml` to insist on numpy 1.16

**Comment by mhvk** [comment]
Sigh, numpy 1.16 is not available on python 3.5

**Comment by mhvk** [comment]
I'm going nuts, now astropy seems too old too...  If the current set doesn't fix it, I'll make a separate PR for updating travis.

**Comment by mhvk** [comment]
OK, I'm trying to fix the PINT issue first in #137

**Comment by luojing1211** [comment]
Should I keep moving forward on this branch? I don't want to make this PR too big to handle.

**Comment by mhvk** [comment]
I think we should merge this one first. I was just hoping to solve the PINT issue, but really that is unrelated.

But are you happy with the changes I made?

**Comment by luojing1211** [comment]
They look much simpler. So I vote yes.
-Jing

**Comment by mhvk** [comment]
OK, I'll remove some of the work-arounds in `.travis.yml` then and push up a version that only does the PINT check as part of `cron`.

**Pull request merged**
