### PR TITLE
Add a resample task.

### PR DESCRIPTION
**Pull request by mhvk**
Partially addresses #100.

@theXYZT - would this be what you were looking for, for extracting B1937 giant pulses?

### CODE REVIEW

**Comment by theXYZT** [comment]
What does this exactly do? The name suggests that this is meant to be a "resampling" task. But you mentioned "extracting giant pulses", so I am slightly confused.

**Comment by mhvk** [comment]
It is resampling - and perhaps I should change the name accordingly.  Its there because you said you wanted to be able to extract a giant pulse centred to sub-sampled precision.

**Comment by luojing1211** [comment]
Does the "Resample" task also do down sampling?

**Comment by mhvk** [comment]
> Does the "Resample" task also do down sampling?

Definitely not as written. Right now, one could do that with `Channelize` + `GetItem` + `Dechannelize`. Is it helpful to have it?

**Pull request merged**
