### PR TITLE
Add pyfftw to Coveralls.

### PR DESCRIPTION
**Pull request by cczhu**
Test to see if we can add pyfftw to Coveralls.

### CODE REVIEW

**Comment by mhvk** [comment]
But, OOPS, this gives a bug - I think we saw this before...

**Comment by cczhu** [comment]
Revised, but let's wait to see if Coveralls improves before merging.

**Comment by cczhu** [comment]
Okay, FINALLY figured this out, and will merge once tests clear.

**Comment by cczhu** [comment]
By the way @mhvk, I think if we toggle "Build pushed branches" on Travis for scintillometry, it'll auto-build whenever something is pushed to master, which will keep all the badges up-to-date.

**Pull request merged**
